### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by gittrekt**
Updated Dockerfile that uses a scratch image so that the only running executable is Java/Signum-Node

Please comment on ideas/questions

Testing has only been done on podman 
(podman run --rm --detach --name node --mount type=bind,src=/signum-node/conf,target=/conf,relabel=shared,U=true,ro=true localhost/signum-node:devel) 
Screenshot from 2024-01-12 10-43-38

- Should work on docker the same but an actual test run would be good.

### CODE REVIEW

**Comment by ohager** [comment]
thanks - will test it and adjust according to the new gradle file. What is that jdeps for?

**Comment by gittrekt** [comment]
It uses Java's jdeps during the build process to create a text file of the
core Java modules being used. That way later on when jlink is used to
create a slimmed down version of Java it only uses what's needed by the
node. Due to the way the jar is being packed I couldn't figure out how to
get jdeps to work properly, and that addon just worked. You could remove
that package if you can get jdeps to work with the node jar, or if you know
for sure that core modules will never change you could use a static list.
It's beneficial so that java is only around 35mb. This image only runs
java, so ldd is used later to include any library's needed for java to run
as well. In the end the only command that can be run in the container is
java, no sh/bash so no simple way to login in.

In the future if I get around to installing docker on a desktop I may also
add support for running the node GUI from the container as well.

I have that image on dockerhub at:
https://hub.docker.com/r/gittrekt/signum-node

**Comment by ohager** [comment]
> It uses Java's jdeps during the build process to create a text file of the core Java modules being used. That way later on when jlink is used to create a slimmed down version of Java it only uses what's needed by the node. Due to the way the jar is being packed I couldn't figure out how to get jdeps to work properly, and that addon just worked. You could remove that package if you can get jdeps to work with the node jar, or if you know for sure that core modules will never change you could use a static list. It's beneficial so that java is only around 35mb. This image only runs java, so ldd is used later to include any library's needed for java to run as well. In the end the only command that can be run in the container is java, no sh/bash so no simple way to login in. In the future if I get around to installing docker on a desktop I may also add support for running the node GUI from the container as well. I have that image on dockerhub at: https://hub.docker.com/r/gittrekt/signum-node

thanks for detailed description. I thought it would be something like shadowjar, which bundles all deps into the resulting jar. 
As we had significant changes on the gradle file I'll need to check that piece.

**Comment by ohager** [comment]
@gittrekt thanks for valuable input. Your ideas are now merged into the new dockerfile under #774 - closing

**Pull request closed without merging**
