### PR TITLE
Format Transaction.java (and dependent code)

### PR DESCRIPTION
**Pull request by damccull**
Did some more code formatting.

### CODE REVIEW

**Comment by ohager** [comment]
I'll be working on Node the next week and will consider your PR

**Comment by damccull** [comment]
> I'll be working on Node the next week and will consider your PR

Yep, no biggie. Just continuing my code format crusade a little at a time. No hurry.

**Comment by ohager** [comment]
> > I'll be working on Node the next week and will consider your PR
> 
> Yep, no biggie. Just continuing my code format crusade a little at a time. No hurry.

I like your new Avatar :+1:

**Comment by damccull** [comment]
> I like your new Avatar 👍

Thanks

**Pull request merged**
