### PR TITLE
Updated Dockerfiles

### PR DESCRIPTION
**Pull request by ohager**
The new Dockerfile. 

- lightweight image (178MB) with @gittrekt custom JRE build :pray: 
- Using now build arguments to address different flavors (h2-testnet, postgres-mainnet, etc)
- Updated Docker.md

At this very moment, only H2 works without pain. We need to work on database connection issue for RDBMS.
The github action to push built images to dockerhub are disabled temporarily.

This PR is the basis for the missing points.

Thanks to @damccull and @gittrekt for support.

### CODE REVIEW

**Comment by ohager** [comment]
> @ohager different images for h2 and maria/post won't be needed with my proposed docker image.
> 
> Also as a reminder there is a known bug in flyway-core 8.2.1-8.3 that containers won't be able to resolve other containers names so may not be able to connect to containers hosting mariadb or postgress.

Ok. So, I need to review that. I had some issue with your proposal due to the need of nodejs (gradle has now the openapi build) embedded. As I got rusty on Docker and needed to relearn some stuff, I'll review.

Keep in mind that we want the possibility to auto-update the wallets (and much more in the next release V4) on containers restart.

Thanks for help

**Comment by ohager** [comment]
> @ohager different images for h2 and maria/post won't be needed with my proposed docker image.
> 
> Also as a reminder there is a known bug in flyway-core 8.2.1-8.3 that containers won't be able to resolve other containers names so may not be able to connect to containers hosting mariadb or postgress.

Just adding: fyway is on version 8.5.13

**Comment by gittrekt** [comment]
> Ok. So, I need to review that. I had some issue with your proposal due to the need of nodejs (gradle has now the openapi build) embedded. As I got rusty on Docker and needed to relearn some stuff I had only slow progress yet.
> 
> The issue with the connection to databases should be tackled. We cannot update flyway to V9 at this moment, as this causes breaking changes inside the code base.
> 
> Keep in mind that we want the possibility to auto-update the wallets (and much more in the next release V4) on containers restart.
> 
> Thanks for help

Depending on how often the image you chose is updated it mag be beneficial to install nodejs in the builder instead of using a pre-built image. I believe I saw last updated 3mo ago so would be wise to look into that option. I can take a look at adding nodejs, and make sure things work on image build.  

I built my container with security as my starting goal. That means I didn't want anything other then java/signum running and that way I could run the container with proper separation from the host system. The separation looses value when you add in bash/sh to automatically update the wallets as it currently runs, so i opted to make sure the build updated things and that was it. I'm not a java developer so no idea how complex it would be, but maybe we can look at creating a function in the node that can perform the updates on startup?

**Comment by ohager** [comment]
> > Ok. So, I need to review that. I had some issue with your proposal due to the need of nodejs (gradle has now the openapi build) embedded. As I got rusty on Docker and needed to relearn some stuff I had only slow progress yet.
> > The issue with the connection to databases should be tackled. We cannot update flyway to V9 at this moment, as this causes breaking changes inside the code base.
> > Keep in mind that we want the possibility to auto-update the wallets (and much more in the next release V4) on containers restart.
> > Thanks for help
> 
> Depending on how often the image you chose is updated it may be beneficial to install nodejs in the builder instead of using a pre-built image. I believe I saw last updated 3mo ago so would be wise to look into that option. I can take a look at adding nodejs, and make sure things work on image build.
> 
> I built my container with security as my starting goal. That means I didn't want anything other then java/signum running and that way I could run the container with proper separation from the host system. The separation looses value when you add in (bash/sh, wget, curl, git) to automatically update the wallets as it currently runs, so i opted to make sure the build updated things and that was it. I'm not a java developer so no idea how complex it would be, but maybe we can look at creating a function in the node that can perform the updates on startup?

All valid: There's new stuff regarding for the new web UI coming. And I expect to have frequent updates on the new web ui. Not sure how complex it is to this from inside java. Those are usually pure shell script tasks, like pulling from git, very similar how it is done with phoenix and classic wallet. The main idea is to pull featured dApps (SPAs) directly into the node. For sure, this must be conditional, i.e. not all nodes need to provide all or any dapps.

**Comment by ohager** [comment]
Merging right now....fully enhanced docker support comes on top of this one.

**Comment by gittrekt** [comment]
> > > Ok. So, I need to review that. I had some issue with your proposal due to the need of nodejs (gradle has now the openapi build) embedded. As I got rusty on Docker and needed to relearn some stuff I had only slow progress yet.
> > > The issue with the connection to databases should be tackled. We cannot update flyway to V9 at this moment, as this causes breaking changes inside the code base.
> > > Keep in mind that we want the possibility to auto-update the wallets (and much more in the next release V4) on containers restart.
> > > Thanks for help
> > 
> > 
> > Depending on how often the image you chose is updated it may be beneficial to install nodejs in the builder instead of using a pre-built image. I believe I saw last updated 3mo ago so would be wise to look into that option. I can take a look at adding nodejs, and make sure things work on image build.
> > I built my container with security as my starting goal. That means I didn't want anything other then java/signum running and that way I could run the container with proper separation from the host system. The separation looses value when you add in (bash/sh, wget, curl, git) to automatically update the wallets as it currently runs, so i opted to make sure the build updated things and that was it. I'm not a java developer so no idea how complex it would be, but maybe we can look at creating a function in the node that can perform the updates on startup?
> 
> All valid: There's new stuff regarding for the new web UI coming. And I expect to have frequent updates on the new web ui. Not sure how complex it is to this from inside java. Those are usually pure shell script tasks, like pulling from git, very similar how it is done with phoenix and classic wallet. The main idea is to pull featured dApps (SPAs) directly into the node. For sure, this must be conditional, i.e. not all nodes need to provide all or any dapps.

Sounds like making of an app store in the gui. Would be cool to see.  
I'll check into some java options and if there's anything remotely viable I'll make a proposal.  

Security is first and foremost so anything done should be safe, and if updating through shell is the only option then I'll come up with a solution to use a staticly linked version of sh and delete anything other the sh and busybox for a bit more reduction in image size.

**Comment by damccull** [comment]
It's always possible in Java. In fact this would be fairly easy. It's just downloading some files to specific locations. It's probably better in Java than shell in this case because you can know when dl is complete and trigger a "plugin reload" or whatever is needed to run them.

But why are we including dapps in the node?

**Pull request merged**
